#!/bin/bash

# Syntax: build <Optional Fancy Name Here>
# This simplifies the whole build setup process. It would probably be most 
# helpful to run this in screen (hence the screen-build command).
. build/envsetup.sh
breakfast cm_d710-userdebug
if [ $# -ne 0 ]
then
	export CM_BUILDTYPE="EXPERIMENTAL"
	export CM_EXTRAVERSION=$1
fi
mka bacon >&build-log.`date +%FT%T`

